import * as THREE from 'three';
import {buildArena} from './arena.js?collision=2';
import {Input} from './input.js?shop=6';
import {Player} from './player.js?collision=2';
import {Zombie} from './zombie.js?collision=2';
import {Weapon,GUNS} from './weapon.js?shop=6';
import {AudioFX} from './audio.js';
import {UI} from './ui.js?shop=6';

const PHASES=[{at:0,name:'WARM-UP',interval:2.6,max:4,speed:.8},{at:10,name:'MORE COMPANY',interval:1.9,max:6,speed:.95},{at:20,name:'CLOSING IN',interval:1.45,max:9,speed:1.12},{at:30,name:'THE YARD TURNS',interval:1.2,max:12,speed:1.28},{at:40,name:'HEAVY PRESSURE',interval:.9,max:16,speed:1.48},{at:50,name:'CHAOS MODE',interval:.62,max:22,speed:1.72}];

export class Game {
  constructor(renderer){this.renderer=renderer;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(76,1,.08,90);const arena=buildArena(this.scene);this.bounds=arena.bounds;this.obstacles=arena.obstacles;this.scene.add(this.camera);this.player=new Player(this.camera,this.bounds-1.1,this.obstacles);this.weapon=new Weapon(this.camera);this.audio=new AudioFX();this.ui=new UI();this.state='menu';this.zombies=[];this.fx=[];this.elapsed=0;this.remaining=60;this.score=0;this.kills=0;this.lifetimeKills=this.readCounter('last60-3-lifetime-kills');this.killsSpent=this.readCounter('last60-3-kills-spent');this.ownedWeapons=this.readUnlockedWeapons();this.shots=0;this.hits=0;this.damageWait=0;this.spawnWait=0;this.groanWait=4;this.uiWait=0;this.pausedAt=0;this.shopOpenedAt=0;this.shopReturnState='playing';this.startAt=0;this.last=0;this.dt=0;this.eventText='KEEP MOVING';this.phase=PHASES[0];this.raycaster=new THREE.Raycaster();this.center=new THREE.Vector2(0,0);this.best=this.readBest();this.input=new Input(renderer.domElement,{pause:()=>this.togglePause(),reload:()=>this.reload(),shop:()=>this.openShop(),look:(x,y)=>this.player.look(x,y),lockChange:locked=>{if(this.ui.lockMessage)this.ui.lockMessage.hidden=!this.isPlaying()||locked;},isPlaying:()=>this.isPlaying()});this.ui.updateCareer(this);this.actions();this.resize();new ResizeObserver(()=>this.resize()).observe(renderer.domElement.parentElement);document.addEventListener('contextmenu',e=>e.preventDefault());}
  isPlaying(){return this.state==='playing';}
  readBest(){try{return Number(localStorage.getItem('last60-3d-best')||0);}catch{return 0;}}
  readCounter(key){try{return Math.max(0,Math.floor(Number(localStorage.getItem(key)||0))||0);}catch{return 0;}}
  readUnlockedWeapons(){try{const saved=JSON.parse(localStorage.getItem('last60-3d-unlocked')||'[]');return new Set(['sidearm',...saved.filter(id=>GUNS.some(g=>g.id===id))]);}catch{return new Set(['sidearm']);}}
  get killCredits(){return Math.max(0,this.lifetimeKills-this.killsSpent);}
  saveCareer(){try{localStorage.setItem('last60-3-lifetime-kills',String(this.lifetimeKills));localStorage.setItem('last60-3-kills-spent',String(this.killsSpent));localStorage.setItem('last60-3d-unlocked',JSON.stringify([...this.ownedWeapons]));}catch{}}
  resize(){const r=this.renderer.domElement.getBoundingClientRect();if(!r.width||!r.height)return;this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();}
  actions(){document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{switch(button.dataset.action){case'start':case'restart':this.start();break;case'resume':this.resume();break;case'menu':this.toMenu();break;case'open-shop':this.openShop();break;case'close-shop':this.closeShop();break;}}));document.querySelector('#pause-button').addEventListener('click',()=>this.pause());document.querySelector('#shop-button').addEventListener('click',()=>this.openShop());this.ui.shopItems.addEventListener('click',e=>{const button=e.target.closest('[data-gun]');if(button)this.buyGun(button.dataset.gun);});document.querySelector('#sound-toggle').addEventListener('click',e=>{const on=this.audio.toggle();e.currentTarget.setAttribute('aria-label',on?'Mute sound':'Enable sound');e.currentTarget.querySelector('span').textContent=on?'SOUND ON':'SOUND OFF';});}
  start(){this.clearZombies();this.clearFX();this.player.reset();this.weapon.reset();this.elapsed=0;this.remaining=60;this.score=0;this.kills=0;this.shots=0;this.hits=0;this.spawnWait=1;this.damageWait=0;this.groanWait=4;this.eventText='KEEP MOVING';this.phase=PHASES[0];this.startAt=performance.now();this.last=this.startAt;this.state='playing';this.ui.show('playing');this.ui.updateCareer(this);this.input.lock();this.renderer.domElement.focus();}
  pause(){if(!this.isPlaying())return;this.pausedAt=performance.now();this.state='paused';this.input.unlock();this.ui.show('pause');}
  resume(){if(this.state!=='paused')return;const now=performance.now();this.startAt+=now-this.pausedAt;this.last=now;this.state='playing';this.ui.show('playing');this.input.lock();this.renderer.domElement.focus();}
  togglePause(){if(this.state==='playing')this.pause();else if(this.state==='paused')this.resume();else if(this.state==='shop')this.closeShop();}
  openShop(){if(!['menu','playing','paused'].includes(this.state))return;this.shopReturnState=this.state;this.shopOpenedAt=performance.now();this.state='shop';this.input.unlock();this.ui.renderShop(this,GUNS);this.ui.show('shop');}
  closeShop(){if(this.state!=='shop')return;const now=performance.now(),duration=now-this.shopOpenedAt;if(this.shopReturnState==='menu'){this.state='menu';this.ui.show('menu');return;}if(this.shopReturnState==='paused'){this.pausedAt+=duration;this.state='paused';this.ui.show('pause');return;}this.startAt+=duration;this.last=now;this.state='playing';this.ui.show('playing');this.input.lock();this.renderer.domElement.focus();}
  buyGun(id){const gun=GUNS.find(item=>item.id===id);if(!gun)return;if(this.ownedWeapons.has(id)){this.weapon.equip(id);this.ui.toast(`${gun.short} EQUIPPED`);}else if(this.killCredits<gun.cost){this.ui.toast(`NEED ${gun.cost-this.killCredits} MORE KILLS`);return;}else{this.killsSpent+=gun.cost;this.ownedWeapons.add(id);this.saveCareer();this.weapon.equip(id);this.ui.toast(`${gun.short} UNLOCKED`);}this.ui.renderShop(this,GUNS);this.ui.updateCareer(this);this.ui.update(this);}
  reload(){if(!this.isPlaying())return;if(this.weapon.reload())this.audio.reload();}
  toMenu(){this.state='menu';this.input.unlock();this.clearZombies();this.clearFX();this.ui.show('menu');}
  finish(victory){if(!this.isPlaying())return;this.remaining=victory?0:Math.max(0,this.remaining);this.state=victory?'victory':'gameover';this.input.unlock();const time=victory?60:this.elapsed,accuracy=this.shots?Math.round(this.hits/this.shots*100):0;this.best=Math.max(this.best,time);try{localStorage.setItem('last60-3d-best',String(this.best));}catch{}this.score=Math.round(time*20+this.kills*100+accuracy);this.ui.result({victory,time,kills:this.kills,score:this.score,accuracy,shots:this.shots,hit:this.hits,best:this.best});}
  phaseFor(time){return [...PHASES].reverse().find(p=>time>=p.at)||PHASES[0];}
  spawn(){const side=Math.floor(Math.random()*4),edge=15.8+Math.random()*1.2,along=(Math.random()*2-1)*15;let x,z;if(side===0){x=edge;z=along;}else if(side===1){x=-edge;z=along;}else if(side===2){x=along;z=edge;}else{x=along;z=-edge;}if(Math.hypot(x-this.player.position.x,z-this.player.position.z)<10){x=Math.sign(x||1)*16;z=Math.sign(z||1)*16;}const zombie=new Zombie(this.scene,x,z,this.elapsed);zombie.speed*=this.phase.speed;this.zombies.push(zombie);}
  shoot(){this.shots++;this.player.recoil=.075;this.audio.shot();const objects=[];for(const z of this.zombies)if(!z.dead)objects.push(...z.meshes);const damageByZombie=new Map(),pellets=this.weapon.config.pellets;let firstPoint=null;for(let i=0;i<pellets;i++){this.center.set(pellets===1?0:(Math.random()-.5)*this.weapon.config.spread*2,pellets===1?0:(Math.random()-.5)*this.weapon.config.spread*2);this.raycaster.setFromCamera(this.center,this.camera);const hit=this.raycaster.intersectObjects(objects,false)[0];if(!hit)continue;const zombie=hit.object.userData.zombie;if(zombie&&!zombie.dead){damageByZombie.set(zombie,(damageByZombie.get(zombie)||0)+this.weapon.config.damage/pellets);firstPoint??=hit.point;}}this.center.set(0,0);if(damageByZombie.size){this.hits++;this.audio.hit();this.ui.hit();if(firstPoint)this.spark(firstPoint);for(const [zombie,damage] of damageByZombie){if(!zombie.dead&&zombie.hit(damage)){this.kills++;this.lifetimeKills++;this.saveCareer();this.ui.updateCareer(this);zombie.dispose();this.zombies=this.zombies.filter(z=>z!==zombie);}}}return 'shot';}
  spark(point){for(let i=0;i<3;i++){const mat=new THREE.MeshBasicMaterial({color:0xf2e500});const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.055,0),mat);mesh.position.copy(point);this.scene.add(mesh);this.fx.push({mesh,v:new THREE.Vector3((Math.random()-.5)*2,Math.random()*1.4,(Math.random()-.5)*2),life:.18,mat});}}
  clearFX(){for(const f of this.fx){this.scene.remove(f.mesh);f.mesh.geometry.dispose();f.mat.dispose();}this.fx=[];}
  clearZombies(){for(const z of this.zombies)z.dispose();this.zombies=[];}
  setPhase(){const p=this.phaseFor(this.elapsed);if(p!==this.phase){this.phase=p;this.eventText=p.at>=50?'NO MORE ROOM':'THEY KEEP COMING';this.ui.toast(p.name);this.audio.groan();}}
  update(dt,now){this.dt=dt;this.elapsed=Math.max(0,(now-this.startAt)/1000);this.remaining=Math.max(0,60-this.elapsed);this.setPhase();this.player.update(dt,this.input.movement());this.damageWait=Math.max(0,this.damageWait-dt);this.spawnWait-=dt;this.groanWait-=dt;if(this.spawnWait<=0&&this.zombies.length<this.phase.max){this.spawn();this.spawnWait=this.phase.interval;if(this.groanWait<=0){this.audio.groan();this.groanWait=5+Math.random()*4;}}this.weapon.update(dt,this.input.fireHeld,()=>this.shoot());for(const zombie of this.zombies){const damage=zombie.update(dt,this.player.position,this.zombies,this.bounds,this.obstacles);if(damage&&this.damageWait<=0){this.damageWait=.52;if(this.player.damage(damage)){this.finish(false);return;}this.audio.damage();}}
    for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;f.mesh.position.addScaledVector(f.v,dt);f.v.y-=dt*2;if(f.life<=0){this.scene.remove(f.mesh);f.mesh.geometry.dispose();f.mat.dispose();this.fx.splice(i,1);}}
    this.score=Math.round(this.elapsed*20+this.kills*100+(this.shots?this.hits/this.shots*100:0));this.uiWait-=dt;if(this.uiWait<=0){this.ui.update(this);this.uiWait=.08;}if(this.remaining<=0){this.remaining=0;this.finish(true);}}
  frame(now){requestAnimationFrame(t=>this.frame(t));const dt=Math.min(.05,Math.max(0,(now-this.last)/1000));this.last=now;if(this.isPlaying())this.update(dt,now);this.renderer.render(this.scene,this.camera);}
}
