export class UI {
  constructor(){this.hud=document.querySelector('#hud');this.overlay=document.querySelector('#overlay');this.screens=[...document.querySelectorAll('[data-screen]')];this.pauseButton=document.querySelector('#pause-button');this.shopButton=document.querySelector('#shop-button');this.shopItems=document.querySelector('#shop-items');this.shopBalance=document.querySelector('#shop-balance');this.shopLifetime=document.querySelector('#shop-lifetime');this.lifetimeCounter=document.querySelector('#lifetime-kills');this.timer=document.querySelector('#timer');this.health=document.querySelector('#health');this.ammo=document.querySelector('#ammo');this.kills=document.querySelector('#kills');this.phase=document.querySelector('#phase-name');this.weaponStatus=document.querySelector('#weapon-status');this.event=document.querySelector('#event-copy');this.toastNode=document.querySelector('#toast');this.lockMessage=document.querySelector('#lock-message');this.vignette=document.querySelector('#damage-vignette');this.hitMarker=document.querySelector('#hit-marker');this.toastLeft=0;this.damageOn=false;this.hitOn=false;}
  show(name){document.documentElement.classList.toggle('game-playing',name==='playing');this.overlay.hidden=name==='playing';this.screens.forEach(s=>s.hidden=s.dataset.screen!==name);this.hud.hidden=name!=='playing';this.pauseButton.hidden=name!=='playing';this.shopButton.hidden=['shop','victory','gameover'].includes(name);this.lockMessage.hidden=true;}
  updateCareer(g){const lifetime=String(g.lifetimeKills),available=String(g.killCredits);this.lifetimeCounter.textContent=lifetime;this.shopLifetime.textContent=lifetime;this.shopBalance.textContent=available;}
  update(g){this.timer.textContent=Math.max(0,g.remaining).toFixed(1).padStart(4,'0');const hp=Math.max(0,Math.min(100,g.player.health));this.health.setAttribute('aria-valuenow',Math.round(hp));[...this.health.children].forEach((el,i)=>el.classList.toggle('empty',hp<(i+1)*10));this.ammo.innerHTML=`${g.weapon.mag} <small>/ ${g.weapon.reserve}</small>`;this.kills.textContent=`${g.kills} ${g.kills===1?'KILL':'KILLS'}`;this.updateCareer(g);this.phase.textContent=g.phase.name;this.event.textContent=g.eventText;this.weaponStatus.textContent=g.weapon.reloading?`RELOADING ${Math.max(0,g.weapon.reloadLeft).toFixed(1)}s`:`${g.weapon.mag?g.weapon.config.short:'EMPTY MAG'} / ${g.weapon.mag?'READY':'PRESS R'}`;this.lockMessage.hidden=g.state!=='playing'||g.input.locked;if(this.toastLeft>0)this.toastLeft-=g.dt;this.toastNode.classList.toggle('visible',this.toastLeft>0);this.vignette.classList.toggle('hit',g.player.damageFlash>0);if(this.hitOn){this.hitLeft-=g.dt;if(this.hitLeft<=0){this.hitOn=false;this.hitMarker.classList.remove('show');}}}
  renderShop(g,guns){this.updateCareer(g);this.shopItems.innerHTML=guns.map(gun=>{const owned=g.ownedWeapons.has(gun.id),equipped=g.weapon.id===gun.id,affordable=g.killCredits>=gun.cost,label=equipped?'EQUIPPED':owned?'EQUIP':`BUY · ${gun.cost} ${gun.cost===1?'KILL':'KILLS'}`;return `<article class="shop-card${equipped?' equipped':''}"><p class="shop-card-index">ARMORY / ${String(guns.indexOf(gun)+1).padStart(2,'0')}</p><h3>${gun.name}</h3><p class="shop-desc">${gun.description}</p><div class="shop-specs"><span>${gun.magSize} ROUND MAG</span><span>${gun.pellets>1?`${gun.pellets} PELLET SPREAD`:`${gun.damage} DAMAGE`}</span></div><button class="shop-buy" data-gun="${gun.id}" ${equipped||(!owned&&!affordable)?'disabled':''}>${label}<span>${owned?'✓':'↗'}</span></button></article>`;}).join('');}
  toast(text){this.toastNode.textContent=text;this.toastLeft=1.4;}
  hit(){this.hitOn=true;this.hitLeft=.15;this.hitMarker.classList.remove('show');void this.hitMarker.offsetWidth;this.hitMarker.classList.add('show');}
  result({victory,time,kills,score,accuracy,shots,hit,best}){document.querySelector('#result-eyebrow').textContent=victory?'ONE MINUTE IN THE YARD':'THAT’S ENOUGH FOR TODAY';document.querySelector('#result-title').innerHTML=victory?'SURVIVED<span class="period">.</span>':'GAME OVER<span class="period">.</span>';document.querySelector('#result-reason').textContent=victory?'The yard is quiet. For now.':'The horde got through.';document.querySelector('#result-time').textContent=victory?'60.00':time.toFixed(1);document.querySelector('#result-kills').textContent=String(kills);document.querySelector('#result-score').textContent=String(score);document.querySelector('#result-best').textContent=best.toFixed(1);document.querySelector('#result-extra').textContent=`${accuracy}% ACCURACY  ·  ${hit} HITS / ${shots} SHOTS`;this.show('result');}
}
